# Generated by Django 6.0.7 on 2026-07-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'assigned'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('passed', 'passed'), ('failed_exhausted', 'failed_exhausted')], default='assigned', max_length=20)),
                ('attempts_used', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='employees.employee')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('employee', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('session_id', models.CharField(blank=True, default='', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='reading_gate.enrollment')),
            ],
            options={
                'verbose_name_plural': 'audit events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulated_time', models.PositiveIntegerField(default=0, help_text='Accumulated active reading time, seconds')),
                ('reached_section', models.PositiveIntegerField(default=1)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('session_id', models.CharField(blank=True, default='', max_length=120)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='reading_gate.enrollment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.section')),
            ],
            options={
                'ordering': ['enrollment', 'section'],
                'unique_together': {('enrollment', 'section')},
            },
        ),
    ]
