# Generated by Django 6.0.7 on 2026-07-28 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_enrollments_to_versions(apps, schema_editor):
    Enrollment = apps.get_model('reading_gate', 'Enrollment')
    Course = apps.get_model('courses', 'Course')

    active_versions = dict(Course.objects.values_list('id', 'active_version_id'))
    for enrollment in Enrollment.objects.all():
        Enrollment.objects.filter(pk=enrollment.pk).update(
            course_version_id=active_versions.get(enrollment.course_id),
            cycle=1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_unique_together_course_is_archived_and_more'),
        ('employees', '0003_employee_current_position'),
        ('reading_gate', '0002_expediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.courseversion'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='source',
            field=models.CharField(default='position', max_length=30),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('in_progress', 'in_progress'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('complete', 'complete'), ('passed', 'passed'), ('failed_exhausted', 'failed_exhausted')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('in_progress', 'in_progress'), ('paused', 'paused'), ('cancelled', 'cancelled'), ('complete', 'complete'), ('passed', 'passed'), ('failed_exhausted', 'failed_exhausted')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('employee', 'course', 'cycle'), name='unique_employee_course_cycle'),
        ),
        migrations.RunPython(link_enrollments_to_versions, migrations.RunPython.noop),
    ]
