# Generated by Django 6.0.7 on 2026-07-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('template', models.CharField(choices=[('access', 'access'), ('reminder', 'reminder'), ('completion', 'completion')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'email')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('failed', 'failed'), ('skipped', 'skipped')], max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
