# Exported from Render
version: "1"
projects:
- name: FORMACION
  environments:
  - name: Production
    services:
    - type: web
      name: onboarding-formation
      runtime: docker
      repo: https://github.com/correoparaego/onboarding-formation
      plan: free
      region: frankfurt
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
      envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: POSTGRES_HOST
        value: dpg-d9jpgkjeo5us73bsb5eg-a
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: onboarding_lkk7
      - key: POSTGRES_USER
        value: onboarding_user
      - key: POSTGRES_PASSWORD
        sync: false
      - key: DNI_ENCRYPTION_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: "gemini-3.6-flash"
      - key: AI_USE_FAKE_LLM
        value: "false"
      - key: EMAIL_TRANSPORT
        value: "console"
