# Generated by Django 6.0.7 on 2026-07-14 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLLMKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('provider', models.CharField(help_text='Provider label, e.g. openai/groq/ollama', max_length=80)),
                ('base_url', models.URLField(help_text='OpenAI-compatible base URL', max_length=400)),
                ('model', models.CharField(help_text='Model name', max_length=120)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin LLM key',
                'verbose_name_plural': 'admin LLM keys',
            },
        ),
    ]
