# Generated by Django 6.0.7 on 2026-07-28 00:17

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def create_initial_versions(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    CourseVersion = apps.get_model('courses', 'CourseVersion')
    Section = apps.get_model('courses', 'Section')
    QuestionBank = apps.get_model('courses', 'QuestionBank')

    for course in Course.objects.all():
        version = CourseVersion.objects.create(
            course_id=course.id,
            number=1,
            title=course.title,
            min_time_divisor=course.min_time_divisor,
            status='published',
            published_at=timezone.now(),
        )
        Section.objects.filter(course_id=course.id).update(version_id=version.id)
        QuestionBank.objects.filter(course_id=course.id).update(version_id=version.id)
        Course.objects.filter(pk=course.id).update(active_version_id=version.id)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/sections/pdfs/'),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('min_time_divisor', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.course')),
            ],
            options={
                'ordering': ['course', '-number'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_courses', to='courses.courseversion'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='courses.courseversion'),
        ),
        migrations.AddField(
            model_name='section',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.courseversion'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('version', 'order'), name='unique_version_section_order'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='unique_course_version_number'),
        ),
        migrations.RunPython(create_initial_versions, migrations.RunPython.noop),
    ]
