# Generated by Django 6.0.7 on 2026-07-14 17:46

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', common.fields.EncryptedDNIField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
