# Generated by Django 6.0.7 on 2026-07-28 00:17

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def reconcile_positions(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Position = apps.get_model('courses', 'Position')

    for employee in Employee.objects.exclude(position=''):
        position = Position.objects.filter(name__iexact=employee.position).first()
        if position is None:
            base_slug = slugify(employee.position) or 'position'
            slug = base_slug
            suffix = 2
            while Position.objects.filter(slug=slug).exists():
                slug = f'{base_slug}-{suffix}'
                suffix += 1
            position = Position.objects.create(name=employee.position, slug=slug)
        Employee.objects.filter(pk=employee.pk).update(current_position_id=position.id)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_unique_together_course_is_archived_and_more'),
        ('employees', '0002_w1_dni_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='courses.position'),
        ),
        migrations.RunPython(reconcile_positions, migrations.RunPython.noop),
    ]
